ROOT_DIR = $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
DOCKER ?= docker
KUBECONFIG ?= $(HOME)/.kube/config

IMAGE_REGISTRY ?= quay.io
IMAGE_REPO ?= bf2
IMAGE_NAME ?= e2e-test-suite
IMAGE_TAG ?= latest
IMAGE = "${IMAGE_REGISTRY}/${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}"

# Test ENVs
TESTCASE ?=
PROFILE ?=
LOG_DIR ?=
CONFIG_PATH ?=
SERVICE_API_URI ?=
SSO_REDHAT_KEYCLOAK_URI ?=
SSO_REDHAT_REALM ?=
SSO_REDHAT_CLIENT_ID ?=
SSO_REDHAT_REDIRECT_URI ?=
SSO_USERNAME ?=
SSO_PASSWORD ?=
SSO_SECONDARY_USERNAME ?=
SSO_SECONDARY_PASSWORD ?=
SSO_ALIEN_USERNAME ?=
SSO_ALIEN_PASSWORD ?=
SSO_UNAUTHORIZED_USERNAME ?=
SSO_UNAUTHORIZED_PASSWORD ?=
DEV_CLUSTER_SERVER ?=
DEV_CLUSTER_NAMESPACE ?=
DEV_CLUSTER_TOKEN ?=
BF2_GITHUB_TOKEN ?=
CLI_VERSION ?=
CLI_ARCH ?=
REPORTPORTAL_ENABLE ?=
REPORTPORTAL_UUID ?=

ifeq (${DOCKER}, podman)
	DOCKER_RUN = ${DOCKER} run -u "0"
else
	DOCKER_RUN = ${DOCKER} run -u "$(shell id -u)"
endif

ifdef PROFILE
	PROFILE_ARGS = "-P$(PROFILE)"
endif

ifdef TESTCASE
	TESTCASE_ARGS = "-Dtest=$(TESTCASE)"
endif

clean:
	mvn clean

build:
	mvn test -DskipTests

test:
	mvn test $(TESTCASE_ARGS) $(PROFILE_ARGS)

image/build:
	$(DOCKER) build -t ${IMAGE} .

container/test:
	mkdir -p test-results/failsafe-reports
	mkdir -p test-results/logs
	${DOCKER_RUN} \
		-v "${ROOT_DIR}/test-results/failsafe-reports:/home/jboss/test-suite/target/failsafe-reports:z" \
		-v "${ROOT_DIR}/test-results/logs:/home/jboss/test-suite/target/logs:z" \
		-e TESTCASE=${TESTCASE} \
		-e PROFILE=${PROFILE} \
		-e CONFIG_PATH=${CONFIG_PATH} \
		-e SERVICE_API_URI=${SERVICE_API_URI} \
		-e SSO_REDHAT_KEYCLOAK_URI=${SSO_REDHAT_KEYCLOAK_URI} \
		-e SSO_REDHAT_REALM=${SSO_REDHAT_REALM} \
		-e SSO_REDHAT_CLIENT_ID=${SSO_REDHAT_CLIENT_ID} \
		-e SSO_REDHAT_REDIRECT_URI=${SSO_REDHAT_REDIRECT_URI} \
		-e SSO_USERNAME=${SSO_USERNAME} \
		-e SSO_PASSWORD=${SSO_PASSWORD} \
		-e SSO_SECONDARY_USERNAME=${SSO_SECONDARY_USERNAME} \
		-e SSO_SECONDARY_PASSWORD=${SSO_SECONDARY_PASSWORD} \
		-e SSO_ALIEN_USERNAME=${SSO_ALIEN_USERNAME} \
		-e SSO_ALIEN_PASSWORD=${SSO_ALIEN_PASSWORD} \
		-e SSO_UNAUTHORIZED_USERNAME=${SSO_UNAUTHORIZED_USERNAME} \
        -e SSO_UNAUTHORIZED_PASSWORD=${SSO_UNAUTHORIZED_PASSWORD} \
        -e DEV_CLUSTER_SERVER=${DEV_CLUSTER_SERVER} \
		-e DEV_CLUSTER_NAMESPACE=${DEV_CLUSTER_NAMESPACE} \
		-e DEV_CLUSTER_TOKEN=${DEV_CLUSTER_TOKEN} \
		-e BF2_GITHUB_TOKEN=${BF2_GITHUB_TOKEN} \
		-e CLI_VERSION=${CLI_VERSION} \
		-e CLI_ARCH=${CLI_ARCH} \
		-e REPORTPORTAL_ENABLE=${REPORTPORTAL_ENABLE} \
		-e REPORTPORTAL_UUID=${REPORTPORTAL_UUID} \
		-e KAFKA_POSTFIX_NAME=${KAFKA_POSTFIX_NAME} \
		${IMAGE}

.PHONY: clean build test image/build container/test