/*
 * Kafka Service Fleet Manager
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.managed.services.test.client.securitymgmt.models;

import com.openshift.cloud.api.kas.models.ServiceAccountList;
import com.openshift.cloud.api.kas.models.ServiceAccountListItem;
import io.vertx.core.json.Json;

import java.util.ArrayList;
import java.util.stream.Collectors;

public class TemporaryServiceAccountList extends ArrayList<TemporaryServiceAccount> {

    @Override
    public String toString() {
        return Json.encode(this);
    }

    public ServiceAccountList toServiceAccountList() {
        return new ServiceAccountList()
            .items(stream().map(i -> new ServiceAccountListItem()
                    .id(i.getId())
                    .clientId(i.getClientId())
                    .name(i.getName())
                    .owner(i.getOwnerId())
                    .createdAt(i.getCreatedAt())
                    .description(i.getDescription()))
                .collect(Collectors.toList()));
    }
}




