/*
 * Kafka Service Fleet Manager
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.managed.services.test.client.securitymgmt.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.openshift.cloud.api.kas.models.ServiceAccountRequest;
import io.vertx.core.json.Json;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Optional;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class TemporaryServiceAccountRequest {
    private String name;
    private String description;

    @Override
    public String toString() {
        return Json.encode(this);
    }

    public static TemporaryServiceAccountRequest fromServiceAccountRequest(ServiceAccountRequest serviceAccountRequest) {
        return new TemporaryServiceAccountRequest(
            serviceAccountRequest.getName(),
            Optional.ofNullable(serviceAccountRequest.getDescription()).orElse("back-compatible description")); // back compatible with null description
    }
}

