/*
 * Kafka Service Fleet Manager
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.managed.services.test.client.securitymgmt.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.openshift.cloud.api.kas.models.ServiceAccount;
import io.vertx.core.json.Json;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.OffsetDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class TemporaryServiceAccount {
    private String id;
    private String clientId;
    private String secret;
    private String name;
    private String description;
    private String ownerId;
    private OffsetDateTime createdAt;

    @Override
    public String toString() {
        return Json.encode(this);
    }

    public ServiceAccount toServiceAccount() {
        return new ServiceAccount()
            .id(id)
            .clientId(clientId)
            .clientSecret(secret)
            .name(name)
            .description(description)
            .owner(ownerId)
            .createdAt(createdAt);
    }
}

